---
driver:
  name: docker

provisioner:
  name: chef_zero
  data_bags_path: 'test/integration/data_bags'

platforms:
  - name: ubuntu-14.04

suites:
  - name: base
    run_list: [
      'recipe[rubygems]'
    ]
  - name: balancer
    run_list: [
      'recipe[rubygems]',
      'recipe[rubygems-balancer]'
    ]
  - name: database
    run_list: []
  - name: app
    run_list: [
      'recipe[rubygems]',
      'recipe[rubygems-app]',
      'recipe[rubygems-app::unicorn]',
      'recipe[rubygems-app::nginx]'
    ]
  - name: cache
    run_list: [
      'recipe[rubygems-cache]'
    ]
