AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  Exclude:
    - vendor/**/*
    - /**/files/**/*
    - cookbooks/rubygems-chef/templates/default/slack.rb

Encoding:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
NumericLiterals:
  Enabled: false
LineLength:
  Enabled: false
Style/WordArray:
  MinSize: 3
Style/RescueModifier:
  Enabled: false

Style/AndOr:
  Exclude:
    - cookbooks/dnsimple/providers/record.rb
Style/Next:
  Exclude:
    - cookbooks/dnsimple/providers/record.rb
